nginx:
    build: ./nginx
    ports:
        - 4000:80
    links:
        - php
    volumes_from:
        - app

php:
    build: ./php
    expose:
        - 9000
    # links:
    #     - mysql
    volumes_from:
        - app
    environment:
        APPLICATION_ENV: docker

app:
    image: php:5.6.30-fpm
    volumes:
        - ../api:/var/www/html
    command: "true"

# mysql:
#     image: mysql:latest
#     volumes:
#         - ./etd/src/resources/sql:/docker-entrypoint-initdb.d
#     volumes_from:
#         - data
#     environment:
#         MYSQL_ROOT_PASSWORD: secret
#         MYSQL_DATABASE: etd
#         MYSQL_USER: etd_service
#         MYSQL_PASSWORD: cuboulder
#
# data:
#     image: mysql:latest
#     volumes:
#         - /var/lib/mysql
#     command: "true"

# phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     ports:
#         - 8080:80
#     links:
#         - mysql
#     environment:
#         PMA_HOST: mysql
